services:
  postgres:
    image: postgres:17
    container_name: epicollect_staging_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: epicollect_staging
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_staging_data:/var/lib/postgresql/postgres_staging_data
      - ./database/migrations:/docker-entrypoint-initdb.d
  
volumes:
  postgres_staging_data: